### ISSUE TITLE
Possible bug in dark mode logic

### ISSUE THREAD

**Issue by davelab6** [googlefonts/variable-fonts#138]
<img width="1182" alt="Screen Shot 2020-02-25 at 12 00 58 PM" src="https://user-images.githubusercontent.com/261579/75289408-37e6ea80-57ec-11ea-8d06-df37ce2631cb.png">

somehow this (text color white) happened to a colleague once but on a hard refresh it was no longer reproducible...

**Comment by jpamental** [comment]
This is a known issue when viewing in dark mode. The issue was introduced with the new design elements in the headers. I'm going to address it on the 'about this site' page but @kennethormandy had said he knew about this and was going to be working on it so I don't want to duplicate efforts if he's in the middle of it on the others.

Kenneth—let me know if it's helpful for me to look at this one.

**Comment by jpamental** [comment]
Ended up being a pretty quick fix, so it's already deployed

**Comment by davelab6** [comment]
Million thanks!
